### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by rayrny** [jerimo/jerimo.github.io#1]
- 프로필에 email 두개 > 첫 줄 이메일 지우기
- description에 세종대 적기
- log >> DevLog
- 폰트 > 나눔 고딕 코딩

**Comment by rayrny** [comment]
> e1212e6

email 중복 수정

**Comment by jerimo** [comment]
> email 중복 수정

**Comment by rayrny** [comment]
> 3f6a59c
description 수정 완료

**Comment by rayrny** [comment]
> 9486a2a
폰트 적용 완료

**Comment by rayrny** [comment]
> fe05171
title 수정 완료
subtitle 삭제
