### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by rayrny** [jerimo/jerimo.github.io#7]
01/29
 - 이것이 코딩테스트다 책 이미지 넣기
 - title 수정: [그리디 ]> [Ch.03] ?? 고민.. 
 - 차라리 문제 이름말고 제목에 문제 번호를 적는건??
 - 백준 11047 그리디 정리해서 포스팅

**Comment by rayrny** [comment]
- 이것이 코딩테스트다 책 이미지 넣기 > 3d4b4ff789a23f9468da47619232f4ae09d28a38

- title 수정: [그리디 ]> [Ch.03] ?? 고민..

- 차라리 문제 이름말고 제목에 문제 번호를 적는건?? > 9d8ee891ef05bdab820c3d181948f6a053eb48e2

- 백준 11047 그리디 정리해서 포스팅 > 9b40c7f8d34bfce84be87faf792c0db939a22959

**Comment by rayrny** [comment]
toc 적용 안되는 문제 해결하기

**Comment by jerimo** [comment]
표 색상 바꾸기 > 이거 small 태그 붙였을때랑 같은 색인거 같음

**Comment by jerimo** [comment]
표 색상 해결

**Comment by rayrny** [comment]
** 사이드바랑 전체 포스트 구조 수정
> https://github.com/C17AN/C17AN.github.io/blob/master/_data/navigation.yml

**Comment by rayrny** [comment]
검색 기능 만들기

**Comment by rayrny** [comment]
사이드바는 어느정도 완료
근데 카테고리 이름에 +같은거 있으면 {% assign posts = site.categories.C언어 %}여기서 인식을 못함 ㅜㅜ

한글도 인식 못함

카테고리는 C로 해두고 아카이브에서 볼때만 C/C++로 표시하는 방법없나..?

**Comment by rayrny** [comment]
슬래쉬, 공백 확인

카테고리 여러개 가능하다는데
그럼 c, c++에 한정해서
카테고리 -c, -c/c++하고
사이드바에선 c로 사용하는 방법

**Comment by rayrny** [comment]
포스트 링크 수정

**Comment by rayrny** [comment]
포스트 하단 아카이브 누르면 아카이브로 이동하게
지금은 하단에 꼬리가 너무 길다

**Comment by rayrny** [comment]
readme 수정

**Comment by rayrny** [comment]
백준 태그 삭제하기
subtitle 다시 잘 생각해보기

**Comment by rayrny** [comment]
아 진짜 근데 왜 toc안되지..?
